CREATE OR REPLACE TRIGGER trg_insurance_discount
BEFORE INSERT ON BILLING
FOR EACH ROW
DECLARE
    v_coverage NUMBER := 0;
BEGIN
    BEGIN
        SELECT I.COVERAGE_PCT
        INTO v_coverage
        FROM PATIENT_INSURANCE PI
        JOIN INSURANCE I
          ON PI.INSURANCE_INSURANCE_ID = I.INSURANCE_ID
        WHERE PI.PATIENT_PATIENT_ID = :NEW.PATIENT_PATIENT_ID
          AND PI.IS_PRIMARY = 'Y'
          AND ROWNUM = 1;

    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            v_coverage := 0;
    END;

    :NEW.DISCOUNT := (:NEW.TOTAL_AMOUNT * v_coverage) / 100;
    :NEW.NET_AMOUNT := :NEW.TOTAL_AMOUNT - :NEW.DISCOUNT;
END;
/