CREATE OR REPLACE TRIGGER trg_duplicate_booking
BEFORE INSERT ON APPOINTMENT
FOR EACH ROW
DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO v_count
    FROM APPOINTMENT
    WHERE PATIENT_PATIENT_ID = :NEW.PATIENT_PATIENT_ID
      AND EMPLOYEE_SCHEDULE_BRIDGE_ID = :NEW.EMPLOYEE_SCHEDULE_BRIDGE_ID
      AND APPOINTMENT_DATE = :NEW.APPOINTMENT_DATE
      AND APPOINTMENT_TIME = :NEW.APPOINTMENT_TIME
      AND STATUS <> 'CANCELLED';

    IF v_count > 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'Duplicate appointment not allowed');
    END IF;
END;
/