SELECT 'DEPARTMENT' AS tbl, COUNT(*) AS cnt FROM DEPARTMENT
UNION ALL SELECT 'EMPLOYEE', COUNT(*) FROM EMPLOYEE
UNION ALL SELECT 'PATIENT', COUNT(*) FROM PATIENT
UNION ALL SELECT 'ROOM', COUNT(*) FROM ROOM
UNION ALL SELECT 'BED', COUNT(*) FROM BED
UNION ALL SELECT 'INSURANCE', COUNT(*) FROM INSURANCE
UNION ALL SELECT 'PATIENT_INSURANCE', COUNT(*) FROM PATIENT_INSURANCE
UNION ALL SELECT 'DOCTOR_SCHEDULE', COUNT(*) FROM DOCTOR_SCHEDULE
UNION ALL SELECT 'EMPLOYEE_SCHEDULE', COUNT(*) FROM EMPLOYEE_SCHEDULE
UNION ALL SELECT 'DOCTOR_VACATION', COUNT(*) FROM DOCTOR_VACATION
UNION ALL SELECT 'APPOINTMENT', COUNT(*) FROM APPOINTMENT
UNION ALL SELECT 'ADMISSION', COUNT(*) FROM ADMISSION
UNION ALL SELECT 'BILLING', COUNT(*) FROM BILLING
UNION ALL SELECT 'PAYMENT', COUNT(*) FROM PAYMENT;