-- =============================================
-- Constraints: UNIQUE, CHECK, FOREIGN KEYS
-- Run as: hms_admin
-- Run AFTER 01_create_tables.sql
-- =============================================

-- UNIQUE constraints
ALTER TABLE PATIENT ADD CONSTRAINT PATIENT_email_UN UNIQUE (email);
ALTER TABLE EMPLOYEE ADD CONSTRAINT EMPLOYEE_email_UN UNIQUE (email);
ALTER TABLE EMPLOYEE ADD CONSTRAINT EMPLOYEE_license_no_UN UNIQUE (license_no);
ALTER TABLE INSURANCE ADD CONSTRAINT INSURANCE_policy_number_UN UNIQUE (policy_number);
ALTER TABLE ROOM ADD CONSTRAINT ROOM_room_number_UN UNIQUE (room_number);

-- CHECK constraints
ALTER TABLE ADMISSION ADD CONSTRAINT adm_status_chk
  CHECK (status IN ('ACTIVE','DISCHARGED','TRANSFERRED'));
ALTER TABLE APPOINTMENT ADD CONSTRAINT appt_status_chk
  CHECK (status IN ('SCHEDULED','COMPLETED','CANCELLED','RESCHEDULED'));
ALTER TABLE BED ADD CONSTRAINT bed_occ_chk
  CHECK (is_occupied IN ('Y','N'));
ALTER TABLE BILLING ADD CONSTRAINT bill_status_chk
  CHECK (status IN ('PENDING','PAID','PARTIALLY_PAID','CANCELLED'));
ALTER TABLE DOCTOR_SCHEDULE ADD CONSTRAINT sched_time_chk
  CHECK (end_time > start_time);
ALTER TABLE DOCTOR_VACATION ADD CONSTRAINT vac_date_chk
  CHECK (end_date >= start_date);
ALTER TABLE EMPLOYEE ADD CONSTRAINT emp_role_chk
  CHECK (role IN ('DOCTOR','NURSE','TECHNICIAN','ADMIN'));
ALTER TABLE INSURANCE ADD CONSTRAINT ins_coverage_chk
  CHECK (coverage_pct BETWEEN 0 AND 100);
ALTER TABLE PATIENT_INSURANCE ADD CONSTRAINT pi_date_chk
  CHECK (valid_to > valid_from);
ALTER TABLE PATIENT_INSURANCE ADD CONSTRAINT pi_primary_chk
  CHECK (is_primary IN ('Y','N'));
ALTER TABLE PAYMENT ADD CONSTRAINT pay_amt_chk
  CHECK (amount > 0);
ALTER TABLE ROOM ADD CONSTRAINT room_type_chk
  CHECK (room_type IN ('GENERAL','ICU','PRIVATE'));
ALTER TABLE EMPLOYEE_SCHEDULE ADD CONSTRAINT emp_sched_status_chk
  CHECK (status IN ('AVAILABLE','UNAVAILABLE','ON_LEAVE'));

-- FOREIGN KEY constraints
ALTER TABLE PATIENT ADD CONSTRAINT PATIENT_GUARDIAN_FK
  FOREIGN KEY (guardian_id) REFERENCES PATIENT (patient_id);
ALTER TABLE EMPLOYEE ADD CONSTRAINT EMPLOYEE_DEPARTMENT_FK
  FOREIGN KEY (DEPARTMENT_department_id) REFERENCES DEPARTMENT (department_id);
ALTER TABLE BED ADD CONSTRAINT BED_ROOM_FK
  FOREIGN KEY (ROOM_room_id) REFERENCES ROOM (room_id);
ALTER TABLE PATIENT_INSURANCE ADD CONSTRAINT PI_PATIENT_FK
  FOREIGN KEY (PATIENT_patient_id) REFERENCES PATIENT (patient_id);
ALTER TABLE PATIENT_INSURANCE ADD CONSTRAINT PI_INSURANCE_FK
  FOREIGN KEY (INSURANCE_insurance_id) REFERENCES INSURANCE (insurance_id);
ALTER TABLE EMPLOYEE_SCHEDULE ADD CONSTRAINT EMP_SCHED_EMP_FK
  FOREIGN KEY (EMPLOYEE_employee_id) REFERENCES EMPLOYEE (employee_id);
ALTER TABLE EMPLOYEE_SCHEDULE ADD CONSTRAINT EMP_SCHED_DOC_SCHED_FK
  FOREIGN KEY (DOCTOR_SCHEDULE_schedule_id) REFERENCES DOCTOR_SCHEDULE (schedule_id);
ALTER TABLE DOCTOR_VACATION ADD CONSTRAINT DOCTOR_VACATION_EMPLOYEE_FK
  FOREIGN KEY (EMPLOYEE_employee_id) REFERENCES EMPLOYEE (employee_id);
ALTER TABLE APPOINTMENT ADD CONSTRAINT APPOINTMENT_PATIENT_FK
  FOREIGN KEY (PATIENT_patient_id) REFERENCES PATIENT (patient_id);
ALTER TABLE APPOINTMENT ADD CONSTRAINT APPT_EMP_SCHED_FK
  FOREIGN KEY (EMPLOYEE_SCHEDULE_bridge_id) REFERENCES EMPLOYEE_SCHEDULE (bridge_id);
ALTER TABLE APPOINTMENT_HISTORY ADD CONSTRAINT APPT_HIST_APPT_FK
  FOREIGN KEY (APPOINTMENT_appointment_id) REFERENCES APPOINTMENT (appointment_id);
ALTER TABLE ADMISSION ADD CONSTRAINT ADMISSION_PATIENT_FK
  FOREIGN KEY (PATIENT_patient_id) REFERENCES PATIENT (patient_id);
ALTER TABLE ADMISSION ADD CONSTRAINT ADMISSION_BED_FK
  FOREIGN KEY (BED_bed_id) REFERENCES BED (bed_id);
ALTER TABLE ADMISSION ADD CONSTRAINT ADMISSION_EMPLOYEE_FK
  FOREIGN KEY (EMPLOYEE_employee_id) REFERENCES EMPLOYEE (employee_id);
ALTER TABLE PRESCRIPTION ADD CONSTRAINT PRESCRIPTION_APPOINTMENT_FK
  FOREIGN KEY (APPOINTMENT_appointment_id) REFERENCES APPOINTMENT (appointment_id);
ALTER TABLE PRESCRIPTION ADD CONSTRAINT PRESCRIPTION_EMPLOYEE_FK
  FOREIGN KEY (EMPLOYEE_employee_id) REFERENCES EMPLOYEE (employee_id);
ALTER TABLE PRESCRIPTION ADD CONSTRAINT PRESCRIPTION_PATIENT_FK
  FOREIGN KEY (PATIENT_patient_id) REFERENCES PATIENT (patient_id);
ALTER TABLE BILLING ADD CONSTRAINT BILLING_PATIENT_FK
  FOREIGN KEY (PATIENT_patient_id) REFERENCES PATIENT (patient_id);
ALTER TABLE BILLING ADD CONSTRAINT BILLING_INSURANCE_FK
  FOREIGN KEY (INSURANCE_insurance_id) REFERENCES INSURANCE (insurance_id);
ALTER TABLE BILLING ADD CONSTRAINT BILLING_ADMISSION_FK
  FOREIGN KEY (ADMISSION_admission_id) REFERENCES ADMISSION (admission_id);
ALTER TABLE BILLING ADD CONSTRAINT BILLING_APPOINTMENT_FK
  FOREIGN KEY (APPOINTMENT_appointment_id) REFERENCES APPOINTMENT (appointment_id);
ALTER TABLE PAYMENT ADD CONSTRAINT PAYMENT_BILLING_FK
  FOREIGN KEY (BILLING_bill_id) REFERENCES BILLING (bill_id);